apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: ajaymagar/nodeapi
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: myapi
spec:
  type: ClusterIP
  selector:
    app: myapi
  ports:
  - port: 5000
    targetPort: 8000
